/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "obstracle_test.ts" instead.
 */

#include <check.h>

#line 1 "obstracle_test.ts"
#include "../src/objects/obstracle.h"

START_TEST(two_equal_obstracles)
{
#line 4
    Hindernis *a = createHindernis(80, 20);
    int expected = 1;
    int result = equals(a, 80, 20);
    ck_assert_int_eq(result, expected);

}
END_TEST

START_TEST(one_different_coordinate)
{
#line 10
    Hindernis *a = createHindernis(80, 20);
    int expected = 0;
    int result = equals(a, 70, 20);
    ck_assert_int_eq(result, expected);

}
END_TEST

START_TEST(two_different_coordinates)
{
#line 16
    Hindernis *a = createHindernis(80, 20);
    int expected = 0;
    int result = equals(a, 70, 10);
    ck_assert_int_eq(result, expected);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, two_equal_obstracles);
    tcase_add_test(tc1_1, one_different_coordinate);
    tcase_add_test(tc1_1, two_different_coordinates);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
